/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package databases;

import org.junit.Test;

import us.jcedeno.college.DatabaseApp;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        // CREATE BETTER TESTS
        DatabaseApp classUnderTest = new DatabaseApp();
        assertNotNull("DB CANNOT BE NULL", classUnderTest.getDatabase());

    }
}
