/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package us.jcedeno.college;

import lombok.Getter;
import us.jcedeno.college.objects.Database;
import us.jcedeno.college.objects.Person;

public class DatabaseApp {
    private @Getter Database database = new Database("database.db");

    public static void main(String[] args) throws Exception {
        var app = new DatabaseApp();
        // Add person to db
        var person = Person.of("Juan", "Cedeno", 19, 123456789, 4000400040001234L);
        app.getDatabase().insertPerson(person);
        // Retrive person from database
        var personBack = app.getDatabase().selectPerson("1");
        System.out.println(personBack.toString());
        // Add another person to DB to show later
        app.getDatabase().insertPerson(Person.of("John", "Wick", 69, 420, 4000200060009000L));
        // List all people in db and print them
        var people = app.getDatabase().findAllPeople();
        System.out.println("People in database: ");
        people.forEach(System.out::println);
        // Delete people
        app.getDatabase().deletePerson(123456789L);
        System.out.println("After delete: ");
        app.getDatabase().findAllPeople().forEach(System.out::println);
    }
}
